# fly.toml app configuration file generated for firebond-ex-api on 2023-07-03T10:41:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "firebond-ex-api"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
